# Generated by Django 5.1.6 on 2025-03-14 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='comment_id',
        ),
        migrations.AddField(
            model_name='comment',
            name='state_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.state'),
        ),
    ]
