# Generated by Django 5.1.6 on 2025-03-16 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_state_comment_id_comment_state_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='name_comment',
        ),
        migrations.AlterField(
            model_name='comment',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.user'),
        ),
    ]
