# Generated by Django 5.1.6 on 2025-03-16 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_comment_name_comment_alter_comment_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user_id',
        ),
    ]
